server:
  port: 8081

app:

  admin:

    email: ${ADMIN_EMAIL:admin@shop.com}

    password: ${ADMIN_PASSWORD:admin123}

    first-name: System

    last-name: Administrator


spring:

  datasource:

    url: jdbc:postgresql://localhost:5432/user_db

    username: postgres

    password: postgres


  jpa:

    hibernate:

      ddl-auto: validate

    show-sql: true


  flyway:

    enabled: true

    locations: classpath:db/migration

jwt:

  secret: 8K8MZ5xXW2X+2slmRrPwL8nN0uM8c2QM5O8P2rVnF0E=

  expiration: 900000

logging:
  level:
    org.flywaydb: DEBUG

